sudo: false
dist: trusty

language: python
python:
    - "3.5"
    - "3.6"

# command to install dependencies
before_install:
    - sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
    - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get install -y docker-ce
install:
    - pip install .
    - python -c 'from stakkr.setup import _post_install; _post_install()'
    - pip install -r requirements.txt

# command to run tests
script: pytest
