version: '2'

networks:
  lamp:
    driver: bridge
    ipam:
        config:
            - subnet: ${DOCKER_SUBNET}
              gateway: ${DOCKER_GATEWAY}

services:
    data:
        image: inetprocess/data
        #build: https://github.com/inetprocess/docker-data
        volumes:
            - ./home/www-data:/home/www-data
            - ./www:/var/www
        networks: [lamp]
        container_name: ${COMPOSE_PROJECT_NAME}_data
        hostname: ${COMPOSE_PROJECT_NAME}_data
