app:
    image: yappabe/data
    volumes:
        - ./home/www-data:/home/www-data
        - ./www:/var/www
    command: '/bin/sh -c "echo Data-only container for PHP files."'

php:
    build: https://git.inetcrm.com/sysadmin/docker-php.git#:${DOCKER_PHP_VERSION}
    # image: inet/php:5.3
    environment:
        FPM_UID: ${DOCKER_UID}
        FPM_GID: ${DOCKER_GID}
    volumes_from:
        - app
    volumes:
        - ./logs/php:/var/log/php

apache:
    build: https://git.inetcrm.com/sysadmin/docker-apache.git#:${DOCKER_APACHE_VERSION}
    # image: inet/apache:2.2
    environment:
        PHP_GID: ${DOCKER_GID}
    volumes_from:
        - app
    volumes:
        - ./logs/apache:/var/log/apache2
    links:
        - php
