app:
    image: yappabe/data
    volumes:
        - ./home/www-data:/home/www-data
        - ./www:/var/www
    command: '/bin/sh -c "echo Data-only container for PHP files."'

php:
    image: inetprocess/php:${DOCKER_PHP_VERSION}
    #build: https://github.com/inetprocess/docker-php#:${DOCKER_PHP_VERSION}
    environment:
        FPM_UID: ${DOCKER_UID}
        FPM_GID: ${DOCKER_GID}
    volumes_from:
        - app
    volumes:
        - ./logs/php:/var/log/php

apache:
    image: inetprocess/apache:${DOCKER_APACHE_VERSION}
    #build: https://github.com/inetprocess/docker-apache#:${DOCKER_APACHE_VERSION}
    environment:
        PHP_GID: ${DOCKER_GID}
    volumes_from:
        - app
    volumes:
        - ./logs/apache:/var/log/apache2
    links:
        - php
