data:
    image: inetprocess/data
    #build: https://github.com/inetprocess/docker-data
    volumes:
        - ./home/www-data:/home/www-data
        - ./www:/var/www

apache:
    image: inetprocess/apache:${DOCKER_APACHE_VERSION}
    #build: https://github.com/inetprocess/docker-apache#:${DOCKER_APACHE_VERSION}
    mem_limit: ${DOCKER_APACHE_RAM}
    environment:
        PHP_GID: ${DOCKER_GID}
    volumes_from: [data]
    volumes:
        - ./logs/apache:/var/log/apache2
    links: [php]

php:
    image: inetprocess/php:${DOCKER_PHP_VERSION}
    #build: https://github.com/inetprocess/docker-php#:${DOCKER_PHP_VERSION}
    mem_limit: ${DOCKER_PHP_RAM}
    environment:
        FPM_UID: ${DOCKER_UID}
        FPM_GID: ${DOCKER_GID}
    volumes_from: [data]
    volumes:
        - ./logs/php:/var/log/php
