version: '2'

services:
    bonita:
        image: bonita:latest
        hostname: bonita-ctn
        links:
            - mysql:mysql
        networks:
            lamp:
                aliases:
                    - bonita-ctn
