version: '2'

services:
    elasticsearch:
        image: elasticsearch:${DOCKER_ELASTICSEARCH_VERSION}
        mem_limit: ${DOCKER_ELASTICSEARCH_RAM}
        hostname: elasticsearch-ctn

    php:
        links:
            - elasticsearch
