version: '2'

services:
    elasticsearch:
        image: elasticsearch:${DOCKER_ELASTICSEARCH_VERSION}
        mem_limit: ${DOCKER_ELASTICSEARCH_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
        hostname: ${COMPOSE_PROJECT_NAME}_elasticsearch
        networks: [lamp]
