version: '2'

services:
    mongoclient:
        image: mongoclient/mongoclient
        links:
            - mongo
        hostname: mongoclient
        networks:
            lamp:
                aliases:
                    - mongoclient-ctn
